### ISSUE TITLE
Verify how collections are related to projects and confirm things are only added to one collection

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-for-science-prj#1311]
Ensure physical things are only added to one collection in the New Project and Update Project workflows, even if a project has more than one collection

**Comment by chrabyrd** [comment]
Projects have a hidden node that can only be accessed programmatically: `Used Set (la:terms/Set) : cc5d6df3-d477-11e9-9f59-a4d18cec433a`

It is only referenced once, in `UpdateResourceListView.add_collection_to_project` [here](https://github.com/archesproject/arches-for-science/blob/dev/1.1.x/arches_for_science/views/update_resource_list.py#L66)
This method is only referenced once, in `UpdateResourceListView.post` [here](https://github.com/archesproject/arches-for-science/blob/dev/1.1.x/arches_for_science/views/update_resource_list.py#L130)
This logic is only run **if the Project does _not_ already have a collection**

A project is determined to have a collection or not by the presence/absence of `collectionresourceid` in the request.
It looks like only one component references the `UpdateResourceListView`, the `add-things-step` [here](https://github.com/archesproject/arches-for-science/blob/dev/1.1.x/arches_for_science/media/js/views/components/workflows/create-project-workflow/add-things-step.js#L122)
The `add-things-step`  populates the `collectionresourceid` value in the POST request by iterating the project's related resources and returning the first value matching the Collection graphid [here](https://github.com/archesproject/arches-for-science/blob/dev/1.1.x/arches_for_science/media/js/views/components/workflows/create-project-workflow/add-things-step.js#L122)
The `add-things-step` is referenced in two places: the `create-project-workflow` and the `project-collection-workflow`.

While it seems technically impossible for a user to assign multiple collections to a Project, it's still worth testing this condition. To do so the graph was updated to un-hide the `Used Set` node, and 2 collections were generated and added to the Project. Progressing through the `Update Project Collection` workflow, the `add-things-step` behaved as expected: it iterated over the project's related resources and returned the first resource that matched the graphid. It appears the collections are sorted by resourceinstance_id. 

So we can safely conclude that if a Project were to somehow have multiple collections, only one would be updated when progressing through the `project-collection-workflow`, and it would be the collection with the lowest alpha-numeric resourceinstance_id every workflow iteration. We can also not worry about the `create-project-workflow` because the user is unable to manually add collections to their project, even when the node is un-hidden.

If we think the could be a potential issue in the future, we should consider giving the user the ability to select which collection to add their objects to in a step preceding the `add-objects-step` in the `project-collection-workflow`. It should be a relatively minor change. However I'd suggest erring on the side of YAGNI for the time being.

**Comment by chrabyrd** [comment]
@chiatt  ^

**Comment by chiatt** [comment]
Good to hear @chrabyrd. Thanks for the great documentation!
