### ISSUE TITLE
AfS models all revert to using "No Template" Header.

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-for-science-prj#1501]
Models no loner use the proper report templates.  However, detail (e.g.: summary reports) accessed via the search page do use the correct template.  After selecting the proper template it is not displayed properly:

![Image](https://github.com/archesproject/arches-for-science/assets/815185/e5bf3a7f-e047-4026-9948-0b5a73907d3b)

![Image](https://github.com/archesproject/arches-for-science/assets/815185/24718beb-006b-4dbf-8e7a-fe3cf7a16102)

**Comment by chiatt** [comment]
The reports in my instances are still the custom reports. I dropped my database and reloaded the app, and it still looks okay. @njkim, could you check and see if your reports have reverted to the no header report. Check the Physical Thing report.

**Comment by chiatt** [comment]
re https://github.com/archesproject/arches-for-science/issues/1036

**Comment by njkim** [comment]
@chiatt My existing disco/afs indeed did not have the report assigned to physical thing. (only the physical thing)
But, I reloaded the package (both afs and test-pkg) it seems all correct now. I am not sure what caused the issue before but I guess at least it's been fixed in the most recent afs.
By the way, all the custom reports in afs do not seem to have the proper preview template.

**Comment by chiatt** [comment]
This should be resolved in the latest
