### ISSUE TITLE
Textual Work instances do not have descriptor names

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-for-science-prj#436]
Textual work descriptors do not display correctly because the primary name template uses <name_content> which does not appear to be a node name in the Name card. Presumably the node name was changed after the function was configured and the function still uses the outdated node name. It seems likely the template should use `<Name (top)_content>` rather than `<Name_content>`

![image.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/7e824577-4e32-4bdf-b9cd-dea7912404a3)

![image.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/c1f20473-8a86-40b4-8656-693997d3b7e0)

**Comment by Habennin** [comment]
So your surmise was correct. Renaming has happened but the  reference field/node does not dynamically change with it. 

Question: shouldn't it? 

Also the node name displayed for specifying from which branch to pull data shows the user facing card name which doesn't have to be unique. This results in ambiguity. Wouldn't it make sense, since this is an administrator facing function, for the field name display for the branch to be the model name and not the card name? Or is this an issue of 'tiles'?

In addition to the field node not dynamically updating being a problem in this case, also it would seem that many of the textual resources don't actually have names from the etl/source.

Looping in @annabelleee  and @lindsgant  into this conversation since it has general implications (like it would likely make sense that all descriptor functions may have been affected by renaming operations) and specific implications (should those textual resources have names from the etl?).

For this fix to stick, I guess it needs to be added to master, would you do that @annabelleee ?

**Comment by chiatt** [comment]
Thanks @Habennin, I agree it would be nice if the function config dynamically updated. There is actually already a ticket for this: archesproject/arches#6169. Unfortunately, given how the function config currently is designed, it's not an easy fix.

I also agree that using the card name in the dropdown can cause some ambiguity. However, we need to use the card name rather than the model name because you can only select a card from the current model for which you are configuring the function. Cards from other models are not available. I can imagine we could use the card name and a node name in combination to provide more clarity instead of just the card name alone.

We probably will need a Name for all Textual Work instances because without it, if a user goes to select a Textual Work from the resource instance select dropdown, they will be presented with a blank line and won't be able to identify which Textual Work they want to relate. The blue line in the image below is an example of a Textual Work that does not have a Name:

![image](https://user-images.githubusercontent.com/1877663/126361963-f1b6f728-3000-4fa6-93c3-6cb286097107.png)

**Comment by chiatt** [comment]
Resolved by in #440
