### ISSUE TITLE
Incorporate Annotation datatype into model(s)

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches-for-science-prj#99]
Steps:
* Determine where annotation should live
* Add cards and down-stream metadata
* Update to_rdf() in datatype to return useful representation rather than embedded geo-json feature for an image

Tag @habennin

**Comment by azaroth42** [comment]
Given that the annotation UI is a _datatype_ that gets associated with some other model, rather than a model by itself, I think that the pattern should be:

* Thing-being-annotated
  * Annotation
    * Body/bodies of annotation -- to discuss the extent of what these are
    * Motivation for annotation (Type, with corresponding Collection in RDM)
    * Creation information for annotation (Creation branch)

The datatype approach means that we need to be careful with the annotation branch to ensure that resources can be annotated by an appropriate set of users, which might not otherwise be able to edit the rest of the resource. A good use of the very granular permissions functionality in arches.  

This also avoids the need to be super clever about the selectors. The annotation selection is always going to be on an image from a IIIF Manifest, but until we need cross-system interoperability (not today), the utility is to be able to align the annotations about physical things with physical thing model, and about digital things with the digital resources model. Later on, we can work out how best to distinguish the targets, given the model that the annotation is associated with, combined with the actual digital target of the part of the image.

Modeling wise, we should stick within core CRM and then map out to Web Annotation if needed for export to other systems. In particular, there isn't an inverse relationship for oa:hasTarget, so we would fall at the first hurdle anyway.

**Comment by azaroth42** [comment]
So my proposal for 1:
 * Annotations should be a branch on Physical Thing, and on Digital Resource.

Meaning it should be a branch of its own to be grafted to each. I will work on this now.

**Comment by azaroth42** [comment]
I think this is the minimal model that we need.

<img width="267" alt="Screen Shot 2020-04-07 at 4 47 35 PM" src="https://user-images.githubusercontent.com/871868/78729718-9923d280-78ef-11ea-8598-2e492536e5d0.png">

(Which I can't export, per https://github.com/archesproject/arches/issues/6071) But seems to work when creating a resource

**Comment by Habennin** [comment]
I can't access the actual branch I guess? But the screenshot is a place to start from...

I'm a bit of a loss as to how this would technically work in Arches. I don't see anything wrong with this modelling in principle or the reasoning above, but how/when does the user use this branch in their workflow? How do they actually relate the annotation to parts of the physical thing? I don't see how they do that with the above (but it could be ignore of mechanisms). The model looks like the metadata for the annotation digital object itself and all seems reasonable enough but the interesting thing, as you mention, is that the annotation connects some data that the user inputs to particular parts of a physical thing.

So, doesn't the user first have to partition the physical thing (potentially having a branch for creating 'features') of the physical object, which they would then refer to in the annotation widget? With the above how do they actually do that?

Other questions: In this branch/model the actual 'thing' from which the branch begins is the 'annotation' and the 'annotation' would be a digital object (if we used those subclasses)? Correct?

If so, does it make sense to put a hidden type on it that distinguishes it as an annotation and or as a digital object? So that it could be retrieved distinctly from any other information object (which is a lot of heterogeneous stuff)?

Annabel has mentioned that they would like to be able to identify/isolate bits of the actual thing (the white part of the priests scarf), and then have the annotation refer this area/part/feature and state something like 'x chemical compond' or 'yellow' both of which would be types. Actually I find that challenging to represent and am not sure that it is covered above. Do I miss obvious things?

Under the assumptions I stated above, I would hypothesise that the physical thing model could have a branch that allows identifying ad hoc features of the object. The user must first subdivide their object into its areas of interest. I would imagine we would want to have a branch and not a resource model because these are not separate objects but truly features in the CRM E25 kind of sense. Once these were created then in an annotation model(?) they could do an annotation activity where they create annotation digital objects and link them to the sub-divided parts of a physical thing (I think I recently saw this feature in Arches as node reference?).  

I can try to sketch all the complexities in a a draw.io diagram or something if that is useful

**Comment by azaroth42** [comment]
The decision to make it a datatype rather than a model has tied our hands for most of these use cases, I'm afraid. There has to be something to attach the annotation branch to, and the only reasonable entity that could be in an annotation model is the target of the annotation. Meaning that the Physical Thing instance representing the white scarf needs to be created before the annotation can be created that shows where it exists in the image.

I could also be missing something about the combination of datatype and cards here too, of course, but the top node of a resource model cannot be an Annotation datatype, it's always the equivalent of semantic.  There isn't even a dropdown to change it.

The yellowness or chemical compound references are, I believe, not in scope for the first round of work, as they would also require a model rather than a datatype. So no, you're not missing anything that they can't be done in a machine comparable way, only as human readable text!

Definitely agree about the hidden type for annotation-ness. I realized that last night as well.

It would be nice to have an auto-deploying instance that could be built from a github branch to show the proposed changes ... :eyes:

**Comment by dwuthrich** [comment]
@azaroth42 I don't follow how making annotation a datatype constrains the modeling.  We need a datatype to manage the connection between IIIF manifests and the geometry(ies) used to identify a region of the IIIF canvas.  But how does that limit the way we model annotations?

**Comment by azaroth42** [comment]
The main issue is that an annotation can't be a resource model, as you can't change the datatype of the top node. Thus it has to be associated with /something/, via some relationship as a branch within another model.  

The options for where annotations could be associated are:
* The body of the annotation -- the comment or tag or similar.
* The target of the annotation -- the thing which the comment is about or the tag is tagging.

Especially with the RDM not being customizable as a model, we couldn't associate an annotation with the body, if it's a concept.  Similarly, we could make the comment the resource as a textual work ... but that seems overkill for this purpose.

Conversely, by using the target of the annotation as the resource that the Annotation datatype is associated with, we limit the complexity by only linking it with entities that we expect to be annotated. This works well for some of the use cases, eg annotating a digital resource that was created as the output of a process, but not so well when the annotated resource should instead be created as part of the annotation process, such as the region of an object of where a sample was taken from.  The sample itself still needs to be created as an instance of a Physical Thing model before it could be annotated as to where it came from.

This is the outcome of the discussion with you and Rob G, no? That we need to get something done, and hence a datatype constrains what we're able to do, but moves the chains with a view to demonstrating progress by end of the financial year. A model is much more flexible, but an equivalent increase in work.

**Comment by dwuthrich** [comment]
Forgive me for being slow on the uptake, but I still don't see why the current datatype precludes creating an Annotation Model.  Yes, the top node would be "semantic", but the model would allow for an annotation branch (with associated nodes as required) and the ability to add a resource instance node to associate it with the annotated thing.

In your example, the downside of using the "target of the annotation" approach appears to be an "order of operations" problem (e.g.: need to create the sample instance before you can annotate it).  This seems like it might not be so problematic in reality.  That is, does it matter if one first creates an annotation of where the sample came from then the sample instance.  Is this different from first creating the sample instance, and only then the annotation instance?

In any case, you are quite right that we discussed focusing on an initial design of the annotation effort to demonstrate progress.  We also recognized that it would highlight areas where our initial assumptions might be overly constraining (and perhaps we're already seeing that).  I just want to make sure that I understand the details that you and George are discussing.

**Comment by azaroth42** [comment]
It definitely doesn't preclude it being included in _some_ model, but what entity does the top semantic node represent when the annotation is the thing in the branch? 

I think the order of operations is indeed the issue ... but you can't (of course) just create a branch without a thing for the branch to be associated with. Without the sample instance, there's nowhere for the annotation to live :)

**Comment by azaroth42** [comment]
To answer my question ... the model could be the activity of creating the annotation, and the branch with the annotation datatype would then be created by it. I don't think that's a good solution to anything other than allowing the annotation to be created independently of anything that it might target.

**Comment by Habennin** [comment]
Hi both,

Spitballing ideas here:

I tried to model the situation diagrammatically here: 

https://drive.google.com/file/d/1n-O1btPVRv39_WshP3WEU1LkHTeszrYV/view?usp=sharing

I then tried out three variants of making this a branch. 

Option 1:

<img width="236" alt="Screenshot 2020-04-14 at 5 52 59 PM" src="https://user-images.githubusercontent.com/12068255/79239072-cf75ca80-7e78-11ea-8c23-a40538bc0dbb.png">

In this scenario, I go with the idea of linking the annotation to what is annotated by attribute assignment. If there were a special annotation class that was E13/E65 the model would be smoother. Basically it then allows you to input what type was assigned to the 'target' or what 'text', indicates what digital resource was used in making the annotation and what observation/experiment allowed this annotation to be made. The actual annotation is produced by a creation event that is initated by the annotating. I don't really know how to add fields off the widget so probably this doesn't work because actually the data will be entered in the widget (what type was assigned/what text etc.)? 

Option II

In this scenario we connect to the thing annotated via an E65 creation event that p16 used the object. The E65 creates the E73 which is the actual annotation. You could then reverse the order of inclusion from E13 to E65 to be e65 to E13 in order to capture the actual attribution information. I did not complete this branch, just sketched the idea for the imagination:

<img width="307" alt="Screenshot 2020-04-14 at 5 59 47 PM" src="https://user-images.githubusercontent.com/12068255/79239885-c0434c80-7e79-11ea-80fb-7135ed955914.png">

Option III:

The root node here is an E73 but the data type is annotation. The connection to the annotated thing would be p128 is about. You could then give all the other information about when it was created, the associated digital files etc. as per option I.

I haven't bothered sketching these branches out in full because I still don't fully grasp if it is possible to add data nodes off the widget and how. 

I think however there is good reason to consider making a linked art class that is E13/E65 called annotation, in order to be able to both create an information object and assign it to something at the same time. 

On this question of the target being created at the time of annotation, is that the only way to go? Is that how the users actually do operate? I mean if what is being annotated in the real world is some part of the real thing, then wouldn't the user before the annotation operation begins already have done some documentation (which they could now do in arches) where they have segmented the object according to their scientific goals and named those regions? If so, the annotation branch or model merely needs to reference these, not create them. 

To explain my thinking, I tried to put together what I imagine would be a hypothetical whole process. You can find this here:

https://docs.google.com/spreadsheets/d/1FaTp_qrNUtehk4WSk3HL-hCbEiVMpIyoIzKt0ZyAlE0/edit?usp=sharing

G

**Comment by chiatt** [comment]
@azaroth42, Is this completed?

**Comment by azaroth42** [comment]
Yes, done. Closing.
